### ISSUE TITLE
Register Bot?

### ISSUE THREAD

**Issue by sqveeze** [warningman/TS-ISLAM#1]
Hi,

I really like all the product of TS-ISLAM, but can you do something like:

Main Channel
- Sub Channel 1 (Male)
- Sub Channel 2 (Female)

If user join Sub Channel 1 (Male) then he receive Male server group
If user join Sub Channel 2 (Female) then user receives Female server group

**Comment by warningman** [comment]
Thank you for the suggestion , will soon activate your request

**Comment by sqveeze** [comment]
Thanks for your reply. Can't wait! Quite a nice job there!
