### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ForgottenEmpire** [warningman/TS-ISLAM#2]
السلام عليكم,
اخوي بوت الساعه ستايل 1 مو راضي يشتغل عدلت كم قلتش بالكونفق و للحينه
بالله شيك و ردلي خبر
اخوانك من, تيم سبيك الإمبراطورية المنسيه.

**Comment by warningman** [comment]
وعليكم السلام ورحمة الله وبركاتة 
ابشر :) بنشوف المشكلة

**Comment by ForgottenEmpire** [comment]
تسلم يالغالي لا اوصيك ببوت اللفل

**Comment by warningman** [comment]
قريباً ان شاء الله

**Comment by ForgottenEmpire** [comment]
استعجل بالله متحمس :)

**Comment by ForgottenEmpire** [comment]
من عندك بوت الاونلاين و الادمن كله شغال يعطيك العافيه

**Comment by warningman** [comment]
ابشر يا الغالي والحين قاعدين نشتغل على بوت مثل السيرفرات الكبيرة بس نعدل فيه بعض الاشياء

**Comment by ForgottenEmpire** [comment]
و يمديك تسوي بوت بين كل فتره و فتره يتغير البنر يعني يكون فيه ملف فيه البنرات و كذا فاهمني اكيد انت

**Comment by warningman** [comment]
يب يمدينا

**Comment by ForgottenEmpire** [comment]
و متى يخلص بوت الساعه؟ متحمس له ههههه

**Comment by warningman** [comment]
بضيفة قريباً , بس قاعد الحين اشتغل على برمجة موقع لكذا مره مشغول باقي 6 ساعات وانا لسة ما خلصت كل الصفحات

**Comment by warningman** [comment]
اول ما اخلص منه باشوف مشاكل بوت الساعة

**Comment by ForgottenEmpire** [comment]
تبرمج موقع و تحطه بالقت هب؟

**Comment by warningman** [comment]
لا , موقع طلب مني برمجتة وقاعد اشتغل عليه

**Comment by warningman** [comment]
حق شركة

**Comment by ForgottenEmpire** [comment]
طيب ابي منك موقع نفس مدل ايست يعني بانل و كذا تجي تس نتفاهم؟

**Comment by ForgottenEmpire** [comment]
و بدفع :)

**Comment by warningman** [comment]
يب هذه الي قاعدين نشتغل عليه بس موقفين علشان المبرمج الثاني "ورننق" مسافر وانا مشغول في برمجة الموقع ابو 6 ساعات

**Comment by warningman** [comment]
ما يختاج تدفع لاني بنزلة اوبن سورس

**Comment by warningman** [comment]
الا لو تبي اضبطلك شكل عليه

**Comment by ForgottenEmpire** [comment]
متى؟

**Comment by ForgottenEmpire** [comment]
عندي انا التصميم يعني ال هتمل و سي اس اس

**Comment by ForgottenEmpire** [comment]
خويي مخلصه

**Comment by ForgottenEmpire** [comment]
بس قصدي يعني اذا ضغط كذا يصير كذا بالتس

**Comment by ForgottenEmpire** [comment]
انت باي تس تتكي؟ عشان متى ما بغيت كلمتك

**Comment by ForgottenEmpire** [comment]
و تذكر نوفا؟ تراه معي بالتس

**Comment by ForgottenEmpire** [comment]
ها بشر؟
